"""Persistence port used by application services."""

from __future__ import annotations

from typing import Protocol

from doc_agent.domain.models import (
    Change,
    DocumentSummary,
    ExtractedDocument,
    Project,
    StoredVersion,
)


class DocumentRepository(Protocol):
    """Persist projects, immutable versions, blocks, visuals, and history."""

    def create_project(self, name: str) -> Project: ...
    def list_projects(self) -> list[Project]: ...
    def get_project(self, project_id: str) -> Project: ...
    def get_document(self, document_id: str) -> DocumentSummary: ...
    def list_documents(self, project_id: str) -> list[DocumentSummary]: ...
    def find_document(self, project_id: str, logical_name: str) -> DocumentSummary | None: ...
    def current_blocks(self, document_id: str) -> list: ...
    def save_version(
        self,
        project_id: str,
        document: ExtractedDocument,
        source_sha256: str,
        changes: list[Change],
        *,
        document_id: str | None = None,
    ) -> StoredVersion: ...
    def history(self, document_id: str) -> list[StoredVersion]: ...
    def get_changes(self, document_id: str, version_number: int) -> list[Change]: ...
    def project_blocks(self, project_id: str) -> list[dict]: ...
    def get_block(self, block_id: str) -> dict: ...
    def list_visuals(self, document_id: str) -> list[dict]: ...
    def get_table_rows(self, document_id: str) -> list[dict]: ...
    def update_visual(
        self, visual_id: str, *, decorative: bool, retrieval_enabled: bool, summary: str | None
    ) -> None: ...
